leftnav:
- identifier: def9aace-758a-f822-40bb-05857530a392
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 9515bca6-7474-82f9-babf-263b152e20af
  name: Readings and Lecture Notes
  url: /pages/readings-and-lecture-notes
  weight: 20
- identifier: 1dae952e-e0bd-39f3-2164-c1c0f7099eab
  name: Assignments
  url: /pages/assignments
  weight: 30
